name: Build and deploy frontend

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: itec_frontend

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./itec-frontend
          push: true
          tags: adelingabriel08/itec-frontend:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy-frontend:
     needs: [ build-frontend ]
     runs-on: ubuntu-latest
     steps:
       - name: Pull & run image on server
         uses: appleboy/ssh-action@master
         with:
           username: ${{ secrets.USERNAME }}
           key: ${{ secrets.SSH_KEY }}
           script: sudo /home/docker/deploy.sh /home/docker/itec/itec-frontend latest
